name: Code Lint
on: 
  push:


jobs: 
  Lint_Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run npm i
        run: npm i
      - name: Run linter
        run: npm run lint 