name: Production Release
on: 
  workflow_dispatch:
    inputs:
      run-desc:
        description: "Run description"
  push:
    branches:
      - main

jobs: 
  Create_Release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"